#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2014 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

set -e

#rm -rf SARibbon
#tar -xvf ./other_lib/SARibbon.tar.xz  -C ./
#cd SARibbon
#cmake .
#make -j 8
#make install
#cd ..

# bash ./clean
# rm -rf build
# rm -rf install.dir
#mkdir build
#mkdir install.dir
#cd build
#cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=../install.dir
mkdir -p ./build
mkdir -p ./install.dir
cmake -B ./build -S . -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=./install.dir
cmake --build ./build
#make install
#cd ..

#rm -rf SARibbon
#make clean
#bash ./clean
