; PXView Windows Installer Script
; Originally generated by HM VNISEdit, rewritten for NSIS 3 Unicode.
; This file must be saved as UTF-8 with BOM for correct Chinese text display.

; --- Enable Unicode installer (NSIS 3+) ---
Unicode true

; --- Product constants ---
!define PRODUCT_NAME "PXView"
; PRODUCT_VERSION can be overridden from the command line:
;   makensis /DPRODUCT_VERSION=1.5.4 window_nisi.nsi
!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "1.6.0"
!endif
!define PRODUCT_PUBLISHER "pxview"
!define PRODUCT_WEB_SITE "http://www.pxview.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\PXView.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

SetCompressor zlib

; ------ MUI Modern Interface (1.67+) ------
!include "MUI.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

; --- Compile-time detection of the PXView Agent (Tauri) binary ---
; Defines PXVIEW_AGENT only if package\PXView-Agent.exe exists when the installer
; is compiled. This keeps local builds working without an extra makensis flag;
; CI also passes /DPXVIEW_AGENT explicitly (see .github/workflows/build.yml).
!tempfile _PXVIEW_AGENT_DETECT
!system 'if exist "package\PXView-Agent.exe" echo !define PXVIEW_AGENT> "${_PXVIEW_AGENT_DETECT}"'
!include /NONFATAL "${_PXVIEW_AGENT_DETECT}"
!delfile "${_PXVIEW_AGENT_DETECT}"

; MUI predefined constants
!define MUI_ABORTWARNING
!define MUI_ICON "logo-win.ico"
!define MUI_UNICON "logo-win.ico"

; Language selection window
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "LICENSE"
; Directory selection page
!insertmacro MUI_PAGE_DIRECTORY
; Installation progress page
!insertmacro MUI_PAGE_INSTFILES
; Installation complete page
!define MUI_FINISHPAGE_RUN "$INSTDIR\PXView.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstallation pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language settings (SimpChinese provides Chinese UI for all standard MUI pages)
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; Reserve files
!insertmacro MUI_RESERVEFILE_LANGDLL
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
; ------ MUI Interface Definition End ------

; ------ i18n LangStrings ------
LangString MsgAppRunning ${LANG_ENGLISH} "PXView is currently running. Please close it before installing."
LangString MsgAppRunning ${LANG_SIMPCHINESE} "PXView 正在运行中，请先关闭后再进行安装。"

LangString MsgPrevDetected ${LANG_ENGLISH} "A previous version of ${PRODUCT_NAME} was detected. It must be removed before installing the new version.$\r$\n$\r$\nDo you want to automatically uninstall the old version now?"
LangString MsgPrevDetected ${LANG_SIMPCHINESE} "检测到旧版本 ${PRODUCT_NAME}，安装新版本前需要先卸载旧版本。$\r$\n$\r$\n是否立即自动卸载旧版本？"

LangString MsgUninstPrepFailed ${LANG_ENGLISH} "Failed to prepare the old uninstaller. Please manually uninstall ${PRODUCT_NAME} from Control Panel and try again."
LangString MsgUninstPrepFailed ${LANG_SIMPCHINESE} "准备卸载程序失败，请从控制面板手动卸载 ${PRODUCT_NAME} 后再试。"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "PXView-Windows-x86_64-Setup-${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES\PXView"
InstallDirRegKey HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
ShowInstDetails show
ShowUnInstDetails show

Var PREV_UNINSTALLER
Var NEED_REBOOT_AFTER_INSTALL

Section "MainSection" SEC01
  ; If PXView-Agent.exe (Tauri desktop wrapper) exists in package, check if it's running
  ${If} ${FileExists} "$INSTDIR\PXView-Agent.exe"
    nsExec::Exec 'cmd /c tasklist /FI "IMAGENAME eq PXView-Agent.exe" /NH | find /I "PXView-Agent.exe"'
    Pop $R0
    ${If} $R0 == 0
      nsExec::Exec 'cmd /c taskkill /F /IM PXView-Agent.exe'
      Sleep 500
    ${EndIf}
  ${EndIf}
  ; If a previous uninstaller was found and executed, reboot if needed
  ${If} $NEED_REBOOT_AFTER_INSTALL == 1
    SetRebootFlag true
  ${EndIf}

  SetOutPath "$INSTDIR"
  ; Force overwrite to ensure all files are updated (not just ifnewer)
  SetOverwrite on
  File "package\PXView.exe"
  CreateDirectory "$SMPROGRAMS\PXView"
  CreateShortCut "$SMPROGRAMS\PXView\PXView.lnk" "$INSTDIR\PXView.exe"
  CreateShortCut "$DESKTOP\PXView.lnk" "$INSTDIR\PXView.exe"
  ; --- Tauri desktop app (PXView Agent) ---
  ; The binary wraps the web UI and spawns PXView.exe --headless. It is placed
  ; alongside PXView.exe so it can find and launch it.
  ;
  ; Guarded at COMPILE time (not a runtime $EXEDIR\package check): the old
  ; ${If} ${FileExists} "$EXEDIR\package\PXView-Agent.exe" only matched when the
  ; installer ran from a folder that still had the package\ tree next to it, so
  ; the standalone downloaded Setup.exe from CI skipped both the binary and the
  ; desktop shortcut. Now PXVIEW_AGENT is defined at compile time (see above)
  ; when the binary exists in package\, so File bakes it in and the shortcuts
  ; are created unconditionally at install time.
  !ifdef PXVIEW_AGENT
    File "package\PXView-Agent.exe"
    CreateShortCut "$SMPROGRAMS\PXView\PXView Agent.lnk" "$INSTDIR\PXView-Agent.exe"
    CreateShortCut "$DESKTOP\PXView Agent.lnk" "$INSTDIR\PXView-Agent.exe"
  !endif
  File /r "package\*.*"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\PXView\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\PXView\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\PXView.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\PXView.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

# -- Per NSIS rules, all Function sections must be placed after Section sections. -- #

; --- Reject shared/system directories as the install target ------------------
; Section Uninstall does RMDir /r on $INSTDIR, so a mistyped target (drive
; root, C:\Windows, Program Files itself, ...) must never be accepted.
; Checked on the directory page (.onVerifyInstDir) and once in .onInit so a
; bad registry value or a /D= override on silent installs falls back to the
; default instead of proceeding. NSIS StrCmp (==) is case-insensitive.
!macro _PXVIEW_CHECK_INSTDIR
  StrCpy $R9 "0"
  StrLen $R0 "$INSTDIR"
  ${If} $R0 <= 3            ; drive root like "C:\" or bare "C:"
    StrCpy $R9 "1"
  ${EndIf}
  ${If} $R9 == "0"
    ${If} $INSTDIR == "$WINDIR"
    ${OrIf} $INSTDIR == "$PROGRAMFILES"
    ${OrIf} $INSTDIR == "$PROGRAMFILES64"
    ${OrIf} $INSTDIR == "$PROGRAMFILES32"
    ${OrIf} $INSTDIR == "$COMMONFILES"
    ${OrIf} $INSTDIR == "$COMMONFILES64"
      StrCpy $R9 "1"
    ${EndIf}
  ${EndIf}
!macroend

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY

  ; --- Check if PXView is running (using built-in nsExec + tasklist, no plugin needed) ---
  nsExec::Exec 'cmd /c tasklist /FI "IMAGENAME eq PXView.exe" /NH | find /I "PXView.exe"'
  Pop $R0
  ${If} $R0 == 0
    MessageBox MB_OK|MB_ICONSTOP "$(MsgAppRunning)" /SD IDOK
    Abort
  ${EndIf}

  ; --- Check for previous installation and uninstall it first ---
  ; Check both 64-bit and 32-bit registry views for backward compatibility.
  ; Old ANSI installers wrote to WOW6432Node (32-bit view); the new Unicode
  ; installer uses the native 64-bit view by default.
  SetRegView 64
  ReadRegStr $PREV_UNINSTALLER HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
  ${If} $PREV_UNINSTALLER == ""
    ; Fall back to 32-bit registry view (for older ANSI installers)
    SetRegView 32
    ReadRegStr $PREV_UNINSTALLER HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
  ${EndIf}
  ; Use 64-bit view for all subsequent registry operations in this installer
  SetRegView 64

  ${If} $PREV_UNINSTALLER != ""
    ; Update $INSTDIR to match the directory of the found uninstaller.
    ; This is necessary when the old install used a different registry view
    ; than what InstallDirRegKey checked at startup.
    ${GetParent} "$PREV_UNINSTALLER" $R1
    StrCpy $INSTDIR "$R1"

    ${If} ${FileExists} "$PREV_UNINSTALLER"
      MessageBox MB_YESNO|MB_ICONQUESTION \
        "$(MsgPrevDetected)" \
        /SD IDYES IDNO abort_install

      ; Copy the old uninstaller to a temp location (because the uninstaller
      ; cannot delete itself while running from $INSTDIR)
      ClearErrors
      CopyFiles /SILENT "$PREV_UNINSTALLER" "$TEMP\_pxview_old_uninst.exe"
      ${If} ${Errors}
        MessageBox MB_OK|MB_ICONSTOP \
          "$(MsgUninstPrepFailed)" \
          /SD IDOK
        Abort
      ${EndIf}

      ; Run the old uninstaller silently
      ClearErrors
      ExecWait '"$TEMP\_pxview_old_uninst.exe" /S _?=$INSTDIR' $R0

      ; Clean up the temp uninstaller copy
      Delete "$TEMP\_pxview_old_uninst.exe"

      ; If the uninstaller requested a reboot, defer it until after install
      ${If} $R0 == 2
        StrCpy $NEED_REBOOT_AFTER_INSTALL 1
      ${EndIf}

      ; Small delay to let file handles release
      Sleep 1000
    ${Else}
      ; Registry key exists but the uninstaller file is missing.
      ; Clean up stale registry keys so they don't interfere with the new install.
      DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"
      DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
    ${EndIf}
  ${EndIf}
  GoTo done

  abort_install:
    Abort

  done:
  ; A forbidden initial $INSTDIR (registry leftover or silent /D= override) is
  ; reset to the default rather than aborting the whole setup.
  !insertmacro _PXVIEW_CHECK_INSTDIR
  ${If} $R9 == "1"
    StrCpy $INSTDIR "$PROGRAMFILES\PXView"
  ${EndIf}
FunctionEnd

; Directory-page guard: refuse forbidden targets while the user browses.
Function .onVerifyInstDir
  !insertmacro _PXVIEW_CHECK_INSTDIR
  ${If} $R9 == "1"
    Abort
  ${EndIf}
FunctionEnd

/******************************
 *  Uninstall section          *
 ******************************/

Section Uninstall
  ; Kill ANY running PXView / PXView-Agent process first. Otherwise locked files
  ; (PXView.exe, plugins, python stdlib, c_decoders DLLs) cannot be deleted and
  ; RMDir /r silently skips them, leaving a half-deleted install tree.
  nsExec::Exec 'cmd /c taskkill /F /IM PXView-Agent.exe' 2>/dev/null
  nsExec::Exec 'cmd /c taskkill /F /IM PXView.exe' 2>/dev/null
  Sleep 300
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\PXView.exe"
  Delete "$INSTDIR\PXView-Agent.exe"

  Delete "$SMPROGRAMS\PXView\Uninstall.lnk"
  Delete "$SMPROGRAMS\PXView\Website.lnk"
  Delete "$DESKTOP\PXView.lnk"
  Delete "$SMPROGRAMS\PXView\PXView.lnk"
  Delete "$DESKTOP\PXView Agent.lnk"
  Delete "$SMPROGRAMS\PXView\PXView Agent.lnk"

  RMDir "$SMPROGRAMS\PXView"

  ; Remove everything under INSTDIR to ensure no stale files remain.
  ; /REBOOTOK marks any still-locked file for deletion on reboot instead of
  ; silently skipping it (a locked PXView.exe etc. would otherwise survive).
  RMDir /r /REBOOTOK "$INSTDIR\styles"
  RMDir /r /REBOOTOK "$INSTDIR\sqldrivers"
  RMDir /r /REBOOTOK "$INSTDIR\res"
  RMDir /r /REBOOTOK "$INSTDIR\printsupport"
  RMDir /r /REBOOTOK "$INSTDIR\plugins"
  RMDir /r /REBOOTOK "$INSTDIR\platforms"
  RMDir /r /REBOOTOK "$INSTDIR\libsigrokdecode"
  RMDir /r /REBOOTOK "$INSTDIR\lang"
  RMDir /r /REBOOTOK "$INSTDIR\imageformats"
  RMDir /r /REBOOTOK "$INSTDIR\iconengines"
  RMDir /r /REBOOTOK "$INSTDIR\generic"
  RMDir /r /REBOOTOK "$INSTDIR\demo"
  RMDir /r /REBOOTOK "$INSTDIR\decoders"
  RMDir /r /REBOOTOK "$INSTDIR\bearer"
  RMDir /r /REBOOTOK "$INSTDIR\translations"
  RMDir /r /REBOOTOK "$INSTDIR\webview2loader"
  RMDir /r /REBOOTOK "$INSTDIR\webui"
  RMDir /r /REBOOTOK "$INSTDIR\Qt*"
  ; Remove any remaining files and subdirectories
  RMDir /r /REBOOTOK "$INSTDIR"

  ; Delete registry keys from the 64-bit view (current SetRegView)
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  ; Also clean up 32-bit registry view in case an older installer wrote there
  SetRegView 32
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetRegView 64
  SetAutoClose true
SectionEnd

# -- Per NSIS rules, all Function sections must be placed after Section sections. -- #

Function un.onInit
  SetRegView 64
  !insertmacro MUI_UNGETLANGUAGE
FunctionEnd

Function un.onUninstSuccess
  HideWindow
FunctionEnd
