; PXView Windows Installer Script
; Originally generated by HM VNISEdit, rewritten as pure ASCII.
; This file is 100% ASCII - no encoding issues with any makensis version.

; --- Product constants ---
!define PRODUCT_NAME "PXView"
!define PRODUCT_VERSION "1.5.4"
!define PRODUCT_PUBLISHER "pxview"
!define PRODUCT_WEB_SITE "http://www.pxview.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\PXView.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

SetCompressor lzma

; ------ MUI Modern Interface (1.67+) ------
!include "MUI.nsh"

; MUI predefined constants
!define MUI_ABORTWARNING
!define MUI_ICON "logo-win.ico"
!define MUI_UNICON "logo-win.ico"

; Language selection window
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "LICENSE"
; Directory selection page
!insertmacro MUI_PAGE_DIRECTORY
; Installation progress page
!insertmacro MUI_PAGE_INSTFILES
; Installation complete page
!define MUI_FINISHPAGE_RUN "$INSTDIR\PXView.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstallation pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language settings (SimpChinese provides Chinese UI for all standard MUI pages)
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; Reserve files
!insertmacro MUI_RESERVEFILE_LANGDLL
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
; ------ MUI Interface Definition End ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "PXView-Windows-x86_64-Setup-${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES\PXView"
InstallDirRegKey HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "package\PXView.exe"
  CreateDirectory "$SMPROGRAMS\PXView"
  CreateShortCut "$SMPROGRAMS\PXView\PXView.lnk" "$INSTDIR\PXView.exe"
  CreateShortCut "$DESKTOP\PXView.lnk" "$INSTDIR\PXView.exe"
  File /r "package\*.*"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\PXView\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\PXView\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\PXView.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\PXView.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

# -- Per NSIS rules, all Function sections must be placed after Section sections. -- #

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

/******************************
 *  Uninstall section          *
 ******************************/

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\PXView.exe"

  Delete "$SMPROGRAMS\PXView\Uninstall.lnk"
  Delete "$SMPROGRAMS\PXView\Website.lnk"
  Delete "$DESKTOP\PXView.lnk"
  Delete "$SMPROGRAMS\PXView\PXView.lnk"

  RMDir "$SMPROGRAMS\PXView"

  RMDir /r "$INSTDIR\styles"
  RMDir /r "$INSTDIR\sqldrivers"
  RMDir /r "$INSTDIR\res"
  RMDir /r "$INSTDIR\printsupport"
  RMDir /r "$INSTDIR\plugins"
  RMDir /r "$INSTDIR\platforms"
  RMDir /r "$INSTDIR\libsigrokdecode"
  RMDir /r "$INSTDIR\lang"
  RMDir /r "$INSTDIR\imageformats"
  RMDir /r "$INSTDIR\iconengines"
  RMDir /r "$INSTDIR\generic"
  RMDir /r "$INSTDIR\demo"
  RMDir /r "$INSTDIR\decoders"
  RMDir /r "$INSTDIR\bearer"
  RMDir /r "$INSTDIR\*"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd

# -- Per NSIS rules, all Function sections must be placed after Section sections. -- #

Function un.onInit
  !insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) has been successfully removed from your computer."
FunctionEnd
