/*
 * This file is part of the PXView project.
 * PXView is based on DSView.
 * PXView is based on PulseView.
 *
 * Copyright (C) 2013 DreamSourceLab <support@dreamsourcelab.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#ifndef PXVIEW_PV_DATA_CSV_HEADER_HINTS_H
#define PXVIEW_PV_DATA_CSV_HEADER_HINTS_H

#include <QRegularExpression>
#include <QString>

#include <cstdint>

namespace pv {
namespace data {
namespace csv_header_hints {

/**
 * What a sigrok/PXView CSV comment block says about the capture.
 *
 * The csv INPUT module (libsigrok) only *strips* comment lines — it never reads
 * them: its samplerate comes from the `samplerate` option or from in-row
 * timestamps, and the channel count from the column layout. But the csv OUTPUT
 * module writes a comment block containing exactly those two facts:
 *
 *     ; CSV generated by PXView 1.6.5
 *     ; from Demo device on ...
 *     ; Channels (32/39): D0, D1, ...
 *     ; Samplerate: 1 MHz
 *
 * That block is generated by libsigrok's csv.c gen_header() (so PulseView
 * writes the same shape) and is the only place the sample rate survives in a
 * CSV. Reading it back lets PXView pre-fill the import dialog instead of
 * falling back to "whatever device happens to be open" — the same round-trip
 * the binary module gets from its file-name hints.
 */
struct Hints {
    int channels = 0;         ///< 0 = not stated by the header
    uint64_t samplerate = 0;  ///< 0 = not stated by the header

    bool empty() const { return channels <= 0 && samplerate == 0; }
};

/**
 * Parse the two fields out of the head of a CSV file.
 *
 * @param head the first few KB of the file (comments live at the very top).
 *
 * Returns nothing unless the text really is a sigrok-style generated CSV: the
 * "CSV generated by" marker must be present, so that an arbitrary text file
 * that merely contains a "Samplerate:" string cannot fake a pre-fill.
 */
inline Hints parse(const QString &head)
{
    Hints hints;

    if (!head.contains(QStringLiteral("CSV generated by")))
        return hints;

    // "; Channels (32/39): D0, D1, ..." — the first number is the number of
    // channels this export carried (the second is the device's total).
    static const QRegularExpression channels_re(
        QStringLiteral("Channels \\((\\d+)\\s*/\\s*(\\d+)\\)"));

    // "; Samplerate: 1 MHz" — gen_header() renders it with
    // sr_samplerate_string() = sr_si_string_u64(), i.e. "<int>[.<frac>] [kMG]Hz"
    // ("999 Hz", "31.5 kHz", "1 MHz", "1.5 GHz").
    static const QRegularExpression samplerate_re(
        QStringLiteral("Samplerate:\\s*(\\d+)(?:\\.(\\d+))?\\s*([kKmMgG]?)\\s*Hz"));

    const QRegularExpressionMatch channels_match = channels_re.match(head);
    if (channels_match.hasMatch()) {
        bool ok = false;
        const int channels = channels_match.captured(1).toInt(&ok);
        if (ok && channels > 0)
            hints.channels = channels;
    }

    const QRegularExpressionMatch samplerate_match = samplerate_re.match(head);
    if (samplerate_match.hasMatch()) {
        bool ok = false;
        const qulonglong whole = samplerate_match.captured(1).toULongLong(&ok);
        if (ok) {
            double value = static_cast<double>(whole);

            const QString fraction = samplerate_match.captured(2);
            if (!fraction.isEmpty()) {
                bool frac_ok = false;
                const qulonglong digits = fraction.toULongLong(&frac_ok);
                if (frac_ok) {
                    double scale = 1.0;
                    for (int i = 0; i < fraction.size(); i++)
                        scale /= 10.0;
                    value += static_cast<double>(digits) * scale;
                }
            }

            const QString prefix = samplerate_match.captured(3).toLower();
            if (prefix == QLatin1String("k"))
                value *= 1000.0;
            else if (prefix == QLatin1String("m"))
                value *= 1000000.0;
            else if (prefix == QLatin1String("g"))
                value *= 1000000000.0;

            if (value > 0.0)
                hints.samplerate = static_cast<uint64_t>(value + 0.5);
        }
    }

    return hints;
}

} // csv_header_hints
} // data
} // pv

#endif // PXVIEW_PV_DATA_CSV_HEADER_HINTS_H
