#ifndef LIBSIGROKDECODE_VERSION_H
#define LIBSIGROKDECODE_VERSION_H

#ifndef SRD_PACKAGE_VERSION_STRING
#define SRD_PACKAGE_VERSION_STRING "0.6.0-git"
#endif

#ifndef SRD_LIB_VERSION_STRING
#define SRD_LIB_VERSION_STRING "4:0:0"
#endif

#endif
