"""
export_helper.py - Helper functions for export/import operations.
"""

from __future__ import annotations

import csv
import os
import struct
from typing import List, Optional

from pxview_automation import McpClient


# The sigrok/PXView csv output module (libsigrok/src/output/csv.c) prefixes the
# data rows with a comment block and a channel-label row, e.g.
#
#     ; CSV generated by PXView 1.6.5
#     ; from <driver> on <ctime>
#     ; Channels (1/32): D0
#     ; Samplerate: 1 MHz
#     D0
#     0
#     1
#     ...
#
# StoreSession pins the module's `label` option to "channel", so the label row
# carries the channel names and *is* the real CSV header. A bare
# csv.DictReader() would take the first comment line as the field names and
# count every later comment line as a data row, shifting the payload down by
# the number of header lines (which is what made the cursor-range data checks
# see a constant sample offset).
CSV_COMMENT_MARKER = ";"


def read_csv_file(filepath: str) -> List[dict]:
    """Read a PXView/sigrok CSV export and return its data rows as dicts.

    Comment lines (leading ``;``, written by the csv output module's
    gen_header()) are dropped first, so the first remaining line — the
    channel-label row — becomes the column header and every returned dict is
    one real sample row.
    """
    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        rows = [line for line in f if not line.startswith(CSV_COMMENT_MARKER)]
    if not rows:
        return []
    return list(csv.DictReader(rows))


def read_binary_file(filepath: str) -> bytes:
    """Read a binary file and return raw bytes."""
    with open(filepath, "rb") as f:
        return f.read()


def find_exported_csv(directory: str, pattern: str = "channel") -> List[str]:
    """Find CSV files matching a pattern in a directory."""
    result = []
    if not os.path.isdir(directory):
        return result
    for f in os.listdir(directory):
        if f.lower().endswith(".csv") and pattern.lower() in f.lower():
            result.append(os.path.join(directory, f))
    return result


def find_exported_binary(directory: str, pattern: str = "channel") -> List[str]:
    """Find binary files matching a pattern in a directory."""
    result = []
    if not os.path.isdir(directory):
        return result
    for f in os.listdir(directory):
        if (f.lower().endswith(".bin") or f.lower().endswith(".dat")
                or pattern.lower() in f.lower()):
            result.append(os.path.join(directory, f))
    return result


def get_logic_sample_bit(samples: bytes, sample_index: int,
                         first_sample: int = 0) -> int:
    """Extract one sample level from a packed logic payload.

    Delegates to ``helpers.sample_helper.logic_bit`` — the single place that
    knows the packed layout.  Pass the response's ``first_sample`` when the
    read did not start at sample 0.  Returns -1 when out of range.
    """
    from helpers.sample_helper import logic_bit

    try:
        return logic_bit(samples, sample_index, first_sample=first_sample)
    except IndexError:
        return -1


def compare_logic_samples(data1: bytes, data2: bytes) -> bool:
    """Compare two logic sample byte arrays for equality."""
    return data1 == data2
